BTL_ASP.NET/BTL_ASP.NET/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_ASP.NET.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }

        public ActionResult Sign_Up()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

    }
}

BTL_ASP.NET/BTL_ASP.NET/Views/HomePage/Index.cshtml
<div class="row">
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-two card-body">
                <div class="stat-content">
                    <div class="stat-text">Sản phẩm bán trong ngày</div>
                    <div class="stat-digit"> <i class="fa "></i>10</div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger w-65" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-two card-body">
                <div class="stat-content">
                    <div class="stat-text">Tổng hóa đơn nhập trong ngày</div>
                    <div class="stat-digit"> <i class="fa "></i>10</div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger w-65" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-two card-body">
                <div class="stat-content">
                    <div class="stat-text">Tổng hóa đơn xuất trong ngày</div>
                    <div class="stat-digit"> <i class="fa "></i>10</div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger w-65" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-two card-body">
                <div class="stat-content">
                    <div class="stat-text">Tổng doanh thu trong ngày</div>
                    <div class="stat-digit"> <i class="fa fa-usd"></i>100.000</div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger w-65" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
        <!-- /# card -->
    </div>
    <!-- /# column -->
</div>

BTL_ASP.NET/BTL_ASP.NET/Views/HomePage/Login.cshtml
<div class="authincation h-100">
    <div class="container-fluid h-100">
        <div class="row justify-content-center h-100 align-items-center">
            <div class="col-md-6">
                <div class="authincation-content">
                    <div class="row no-gutters">
                        <div class="col-xl-12">
                            <div class="auth-form">
                                <h4 class="text-center mb-4">Login in your account</h4>
                                <form action="index.html">
                                    <div class="form-group">
                                        <label><strong>Email</strong></label>
                                        <input type="email" class="form-control" value="login@example.com">
                                    </div>
                                    <div class="form-group">
                                        <label><strong>Password</strong></label>
                                        <input type="password" class="form-control" value="Password">
                                    </div>
                                    <div class="form-row d-flex justify-content-between mt-4 mb-2">
                                        <div class="form-group">
                                            <div class="form-check ml-2">
                                                <input class="form-check-input" type="checkbox" id="basic_checkbox_1">
                                                <label class="form-check-label" for="basic_checkbox_1">Remember me</label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <a href="page-forgot-password.html">Forgot Password?</a>
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary btn-block">Đăng Nhập</button>
                                    </div>
                                </form>
                                <div class="new-account mt-3 ">
                                    <p>Don't have an account? <i class="text-primary">@Html.ActionLink("Đăng Ký", "Sign_Up", "HomePage")</i></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BTL_ASP.NET/BTL_ASP.NET/Views/HomePage/Sign_Up.cshtml
<div class="authincation h-100">
    <div class="container-fluid h-100">
        <div class="row justify-content-center h-100 align-items-center">
            <div class="col-md-6">
                <div class="authincation-content">
                    <div class="row no-gutters">
                        <div class="col-xl-12">
                            <div class="auth-form">
                                <h4 class="text-center mb-4">Sign up your account</h4>
                                <form action="index.html">
                                    <div class="form-group">
                                        <label><strong>Username</strong></label>
                                        <input type="text" class="form-control" placeholder="username">
                                    </div>
                                    <div class="form-group">
                                        <label><strong>Email</strong></label>
                                        <input type="email" class="form-control" placeholder="sign_up@example.com">
                                    </div>
                                    <div class="form-group">
                                        <label><strong>Password</strong></label>
                                        <input type="password" class="form-control" value="Password">
                                    </div>
                                    <div class="settings-form">
                                        <form>
                                            <div class="form-group">
                                                <label>Address</label>
                                                <input type="text" placeholder="1234 Main St" class="form-control">

                                            </div>
                                            <div class="form-row">
                                                <div class="col-md-6">
                                                    <label>Ngày Sinh</label>
                                                    <input type="date" placeholder="" class="form-control">
                                                </div>
                                                <div class="col-md-6">
                                                    <label>Giới Tính</label>
                                                    <form>
                                                        <div class="">
                                                            <label><input type="radio" name="ex" value="1">Nam</label>
                                                            <label><input type="radio" name="ex" value="0">Nữ</label>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label>City</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label>Mã Nhân Viên</label>
                                                    <input type="text" placeholder="123456" class="form-control" readonly>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="text-center mt-4">
                                        <button type="submit" class="btn btn-primary btn-block">Đăng Ký</button>
                                    </div>
                                </form>
                                <div class="new-account mt-3">
                                    <p>Already have an account? <a class="text-primary" href="./Login.html">Đăng Nhập</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--**********************************
    Scripts
***********************************-->
<!-- Required vendors -->
<!--endRemoveIf(production)-->

BTL_ASP.NET/BTL_ASP.NET/Views/Shared/_Header.cshtml
<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                    <div class="search_bar dropdown">
                        <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                            <i class="mdi mdi-magnify"></i>
                        </span>
                        <div class="dropdown-menu p-0 m-0">
                            <form>
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            </form>
                        </div>
                    </div>
                </div>

                <ul class="navbar-nav header-right">
                    <li class="nav-item dropdown header-profile">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                            <i class="mdi mdi-account"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <i href="" class="dropdown-item">
                                <i class="icon-user"> </i>
                                <span class="ml-2">@Html.ActionLink("Profile", "Profile", "HomePage") </span>
                            </i>
                            <i href="#" class="dropdown-item">
                                <i class="icon-key"></i>@Html.ActionLink("Login", "Login", "HomePage")
                            </i>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

BTL_ASP.NET/BTL_ASP.NET/Views/Shared/_Home.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Day la title</title>
    <!-- Favicon icon
        TempData['title']

    -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/images/favicon.png">
    <link rel="stylesheet" href="~/Content/vendor/owl-carousel/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/vendor/owl-carousel/css/owl.theme.default.min.css">
    <link href="~/Content/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <!--Phus-->
    <link href="~/Content/phu/css/StyleProfile.css" rel="stylesheet">


</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="index.html" class="brand-logo">
                <img class="logo-abbr" src="~/Content/images/logo.png" alt="">
                <img class="logo-compact" src="~/Content/images/logo-text.png" alt="">
                <img class="brand-title" src="~/Content/images/logo-text.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        @Html.Partial("_Header");
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        @Html.Partial("_SideBar");
        <!--**********************************
            Sidebar end
        ***********************************-->
        <!--**********************************
            Content body start
        ***********************************-->

        <div class="content-body">
            <!-- row -->
            <div class="container-fluid">
                @RenderBody();

            </div>
        </div>

        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        @Html.Partial("_Footer");
        <!--**********************************
            Footer end
        ***********************************-->
        <!--**********************************
           Support ticket button start
        ***********************************-->
        <!--**********************************
           Support ticket button end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->

    <script src="~/Content/vendor/global/global.min.js"></script>
    <script src="~/Scripts/js/quixnav-init.js"></script>
    <script src="~/Scripts/js/custom.min.js"></script>

    <!-- Vectormap
        <script src="~/Content/vendor/morris/morris.min.js"></script>
        -->
    <script src="~/Content/vendor/raphael/raphael.min.js"></script>
    <script src="~/Content/vendor/morris/morris.min.js"></script>
    <script src="~/Content/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Content/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="~/Content/vendor/gaugeJS/dist/gauge.min.js"></script>

    <!--  flot-chart js -->
    <script src="~/Content/vendor/flot/jquery.flot.js"></script>
    <script src="~/Content/vendor/flot/jquery.flot.resize.js"></script>

    <!-- Owl Carousel -->
    <script src="~/Content/vendor/owl-carousel/js/owl.carousel.min.js"></script>

    <!-- Counter Up -->
    <script src="~/Content/vendor/jqvmap/js/jquery.vmap.min.js"></script>
    <script src="~/Content/vendor/jqvmap/js/jquery.vmap.usa.js"></script>
    <script src="~/Content/vendor/jquery.counterup/jquery.counterup.min.js"></script>
    <script src="~/Scripts/js/dashboard/dashboard-1.js"></script>

    <!--Phu-->
    <script src="~/Content/phu/js/quixnav-init.js"></script>
    <script src="~/Content/phu/js/custom.min.js"></script>

</body>

</html>

BTL_ASP.NET/BTL_ASP.NET/Views/Shared/_SideBar.cshtml
<div class="quixnav">
    <div class="quixnav-scroll">
        <ul class="metismenu" id="menu">
            <li class="nav-label first">MAIN MENU</li>
           

            <li class="nav-label">THÔNG TIN CƠ BẢN</li>
            <!-- Start product information + depot -->
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon icon-app-store"></i><span class="nav-text">Sản Phẩm</span>
                </a>
                <ul aria-expanded="false">
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">Thông tin sản phẩm</a>
                        <ul aria-expanded="false">
                            <li><a href="#">Thông tin sản phẩm</a></li>
                            <li><a href="#">Thêm mới sản phẩm</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Phân loại sản phẩm</a></li>
                </ul>
            </li>

           
            <!-- End product information + warehouse -->


            <li class="nav-label">QUẢN LÝ NHẬP HÀNG</li>
            <!-- Start Manage Depot in -->
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon icon-single-copy-06"></i><span class="nav-text">Quản lý nhập hàng</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="#">Thông tin chi tiết</a></li>
                    <li><a href="#">Thêm thông tin nhập hàng</a></li>
                </ul>
            </li>
            <!-- End Manage Depot in -->

            <li class="nav-label">QUẢN LÝ XUẤT HÀNG</li>
            <!-- Start Manage Depot out-->
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon icon-single-copy-06"></i><span class="nav-text">Quản lý xuất hàng</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="#">Thông tin chi tiết</a></li>
                    <li><a href="#">In thông tin xuất hàng</a></li>
                </ul>
            </li>
            <!-- End Manage Depot out -->

            <li class="nav-label">THỐNG KÊ</li>
            <!-- Start statistical-->
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon icon-world-2"></i><span class="nav-text">Sản phẩm</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="#">Sản phẩm bán chạy</a></li>
                    <li><a href="#">Sản phẩm mới</a></li>
                </ul>
            </li>

            <li>
                <ul aria-expanded="false">
                    <li><a href="#">Hóa đơn nhập</a></li>
                </ul>
            </li>

            <li>
                <ul aria-expanded="false">
                    <li><a href="#">Hóa đơn xuất</a></li>
                </ul>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon icon-world-2"></i><span class="nav-text">Kho</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="#">Thông tin sản phẩm</a></li>
                    <li><a href="#">Lỗi sản phẩm</a></li>
                </ul>
            </li>
            <!-- End statistical -->

        </ul>
    </div>
</div>

<!--


-->